export const ADD_TO_CART = "ADD_TO_CART";

export const UPDATE_CART = "UPDATE_CART";

export const ELIMINATE_ITEM = "ELIMINATE_ITEM";

export const ELIMINATE_ALL_ITEMS = "ELIMINATE_ALL_ITEMS";

export const REQUEST_PRODUCT_DATABASE_PENDING = "REQUEST_PRODUCT_DATABASE_PENDING";

export const REQUEST_PRODUCT_DATABASE_RESOLVED = "REQUEST_PRODUCT_DATABASE_RESOLVED";

export const REQUEST_PRODUCT_DATABASE_REJECTED = "REQUEST_PRODUCT_DATABASE_REJECTED";

export const CHANGE_ROUTE = "CHANGE_ROUTE";

export const LOGIN_PENDING = "LOGIN_PENDING";

export const LOGIN_RESOLVED = "LOGIN_RESOLVED";

export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const REGISTER_PENDING = "REGISTER_PENDING";

export const REGISTER_RESOLVED = "REGISTER_RESOLVED";

export const REGISTER_REJECTED = "REGISTER_REJECTED";

export const LOGIN_RESET = "LOGIN_RESET";
